// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'c': string;
  'flexContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
